name: qminesweeper
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - rich
  - gymnasium
  - pytest
  - pytest-cov
  - typer
  - starlette
  - fastapi
  - jinja2
  - uvicorn
  - pip
  - pip:
      - qiskit
      - stim
