name: qminesweeper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - rich
  - gymnasium
  - flask
  - pytest
  - typer
  - starlette
  - fastapi
  - jinja2
  - uvicorn
  - pip
  - pip:
      - qiskit
      - stim
