[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qminesweeper"
version = "0.1.0"
description = "Quantum Minesweeper Game"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  {name="Andrea Maiani", email="andrea.maiani@su.se"}
  ]
maintainers = [
  {name="Andrea Maiani", email="andrea.maiani@su.se"}
  ]
license = "MIT"
license-files = ["LICENSE"]

dependencies = [
  "numpy",
  "rich",
  "typer>=0.9",
  "fastapi",
  "uvicorn[standard]",
  "jinja2",
  "qiskit",
  "stim",
  "starlette",
  "itsdangerous",
  "python-multipart",
  "python-dotenv",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov"]

[project.urls]
# Homepage = "https://example.com"
# Documentation = "https://readthedocs.org"
Repository = "https://github.com/maiani/quantum-minesweeper.git"
Changelog = "https://github.com/maiani/quantum-minesweeper/blob/master/CHANGELOG.md"

[project.scripts]
qminesweeper = "qminesweeper.cli:main"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["qminesweeper*"]

# Include templates/static in the installed package
[tool.setuptools.package-data]
qminesweeper = ["templates/*.html", "static/*", "static/**/*"]
