# chppy/tableau.py
"""
Stabilizer tableau: the CHP representation and the operations on it.

The package docstring in ``__init__.py`` covers what this library is for, its
gate vocabulary, and the reference. This module documents the representation.

A stabilizer state on n qubits is the unique +1 eigenstate of an abelian
subgroup of the n-qubit Pauli group generated by n independent Paulis.
The CHP representation stores that group — plus n "destabilizer" Paulis that
complete a full basis — as two (2n+1)×n bit matrices X, Z and a phase vector r
of length 2n+1.

Row layout:
    rows  0 .. n-1   destabilizers
    rows  n .. 2n-1  stabilizers
    row   2n         scratch (used during measurement and expectation)

Each row encodes a Pauli P = i^r ⊗_j X_j^{x_{ij}} Z_j^{z_{ij}}.
"""

from __future__ import annotations

import numpy as np

# Supported gate vocabulary, split by arity. These names are this library's
# public gate interface: apply_gate() accepts exactly these strings, and a
# caller wanting different spellings normalises them on its own side.
#
# "dg" suffixes denote the adjoint (Sdg = S-dagger). Callers that hold gates as
# an enum should key it by these strings so no remapping table is needed.
_1Q: frozenset[str] = frozenset({"X", "Y", "Z", "H", "S", "Sdg", "SX", "SXdg", "SY", "SYdg"})
_2Q: frozenset[str] = frozenset({"CX", "CY", "CZ", "SWAP"})


def _gf2_rank(matrix: np.ndarray) -> int:
    """Return the rank of a binary matrix using in-place Gaussian elimination."""
    a = np.array(matrix, dtype=np.uint8, copy=True)
    rank = 0
    for col in range(a.shape[1]):
        pivots = np.flatnonzero(a[rank:, col])
        if pivots.size == 0:
            continue
        pivot = rank + int(pivots[0])
        a[[rank, pivot]] = a[[pivot, rank]]
        for row in range(a.shape[0]):
            if row != rank and a[row, col]:
                a[row] ^= a[rank]
        rank += 1
        if rank == a.shape[0]:
            break
    return rank


def _validate_subset(subset: list[int], n_qubits: int) -> tuple[int, ...]:
    """Check a qubit-index subset and return it sorted and deduplicated.

    Rejects non-lists, non-integers (``bool`` included, since it subclasses
    ``int``), repeated indices, and indices outside ``[0, n_qubits)``. The
    exception types below are part of the public contract: ``TypeError`` for a
    malformed container or element, ``ValueError`` for duplicates, and
    ``IndexError`` for out-of-range indices.
    """
    if not isinstance(subset, list):
        raise TypeError("subset must be a list of integer qubit indices")
    if any(isinstance(q, bool) or not isinstance(q, int) for q in subset):
        raise TypeError("subset must contain only integer qubit indices")
    if len(set(subset)) != len(subset):
        raise ValueError("subset must not contain duplicate qubit indices")
    if any(q < 0 or q >= n_qubits for q in subset):
        raise IndexError(f"subset indices must be in [0, {n_qubits})")
    return tuple(sorted(subset))


class CHP:
    """CHP stabilizer tableau for n qubits (Aaronson–Gottesman 2004).

    State is stored in three numpy arrays:
        x  : uint8 (2n+1, n)  — X bits of each Pauli generator row
        z  : uint8 (2n+1, n)  — Z bits
        r  : uint8 (2n+1,)    — phase bits  (sign = (-1)^r)

    Rows 0..n-1 are destabilizers, n..2n-1 are stabilizers, 2n is scratch.
    Initialised to |0...0⟩: destabilizer_i = X_i, stabilizer_i = Z_i.
    """

    def __init__(self, n_qubits: int) -> None:
        self.n = n_qubits
        self._init_state()

    # ------------------------------------------------------------------
    # Initialisation
    # ------------------------------------------------------------------

    def _init_state(self) -> None:
        n = self.n
        self.x = np.zeros((2 * n + 1, n), dtype=np.uint8)
        self.z = np.zeros((2 * n + 1, n), dtype=np.uint8)
        self.r = np.zeros(2 * n + 1, dtype=np.uint8)
        if n:
            np.fill_diagonal(self.x[0:n], 1)  # destabilizer i = X_i
            np.fill_diagonal(self.z[n : 2 * n], 1)  # stabilizer  i = Z_i

    def reset(self) -> None:
        """Reinitialise to |0...0⟩ (same qubit count)."""
        self._init_state()

    def entanglement_entropy(self, subset: list[int]) -> float:
        """Return ``S(subset : complement)`` for this pure stabilizer state.

        The stabilizer generators supported entirely inside the selected
        region span its local stabilizer subgroup.  If its GF(2) rank is ``r``
        and the region has ``k`` qubits, the reduced-state entropy is ``k-r``
        bits.  Only tableau arrays are read; this query does not alter the
        scratch row or consume measurement randomness.
        """
        region = _validate_subset(subset, self.n)
        k = len(region)
        if not region or k == self.n:
            return 0.0
        if k > self.n - k:
            region = tuple(q for q in range(self.n) if q not in region)
            k = len(region)
        # The projection onto A has rank n - rank(S_complement).  Purity
        # gives S(A) = S(complement) = rank(projected generators) - |A|.
        # Project the smaller side so a single-cell query has only two columns.
        projected = np.concatenate(
            (self.x[self.n : 2 * self.n, list(region)], self.z[self.n : 2 * self.n, list(region)]),
            axis=1,
        )
        return float(_gf2_rank(projected) - k)

    # ------------------------------------------------------------------
    # Convenience: M = 2n (number of real rows, excluding scratch)
    # ------------------------------------------------------------------

    @property
    def _M(self) -> int:
        return 2 * self.n

    # ------------------------------------------------------------------
    # Single-qubit gate primitives (vectorised over all 2n generator rows)
    # ------------------------------------------------------------------

    def _H(self, a: int) -> None:
        """Hadamard on qubit a: swaps X↔Z, flips phase when both are 1."""
        m = self._M
        self.r[:m] ^= self.x[:m, a] & self.z[:m, a]
        col = self.x[:m, a].copy()
        self.x[:m, a] = self.z[:m, a]
        self.z[:m, a] = col

    def _S(self, a: int) -> None:
        """Phase gate S on qubit a: Z → Z, X → iXZ (phase flips when X=Z=1)."""
        m = self._M
        self.r[:m] ^= self.x[:m, a] & self.z[:m, a]
        self.z[:m, a] ^= self.x[:m, a]

    def _Sdg(self, a: int) -> None:
        """S† = S^3."""
        self._S(a)
        self._S(a)
        self._S(a)

    def _X(self, a: int) -> None:
        """Pauli X: flips phase of every row where Z_a = 1."""
        m = self._M
        self.r[:m] ^= self.z[:m, a]

    def _Z(self, a: int) -> None:
        """Pauli Z: flips phase of every row where X_a = 1."""
        m = self._M
        self.r[:m] ^= self.x[:m, a]

    def _Y(self, a: int) -> None:
        """Pauli Y = iXZ."""
        m = self._M
        self.r[:m] ^= self.x[:m, a] ^ self.z[:m, a]

    # ------------------------------------------------------------------
    # Two-qubit gate primitives
    # ------------------------------------------------------------------

    def _CX(self, a: int, b: int) -> None:
        """CNOT: control a, target b."""
        m = self._M
        xa, za = self.x[:m, a], self.z[:m, a]
        xb, zb = self.x[:m, b], self.z[:m, b]
        self.r[:m] ^= xa & zb & (xb ^ za ^ 1)
        self.x[:m, b] ^= xa
        self.z[:m, a] ^= zb

    def _CZ(self, a: int, b: int) -> None:
        """Controlled-Z = H_b · CNOT · H_b."""
        self._H(b)
        self._CX(a, b)
        self._H(b)

    def _CY(self, a: int, b: int) -> None:
        """Controlled-Y = S_b · CNOT · S†_b."""
        self._Sdg(b)
        self._CX(a, b)
        self._S(b)

    def _SWAP(self, a: int, b: int) -> None:
        """SWAP = CX(a,b) · CX(b,a) · CX(a,b)."""
        self._CX(a, b)
        self._CX(b, a)
        self._CX(a, b)

    # ------------------------------------------------------------------
    # √-gates, decomposed into {H, S, CX}. The decompositions are exact up
    # to global phase, which a stabilizer tableau does not represent anyway.
    # Check them by conjugating each Pauli and comparing to the intended
    # Clifford action, or against any independent Clifford simulator.
    # ------------------------------------------------------------------

    def _SX(self, a: int) -> None:
        """√X = H·S·H."""
        self._H(a)
        self._S(a)
        self._H(a)

    def _SXdg(self, a: int) -> None:
        """√X† = H·S†·H."""
        self._H(a)
        self._Sdg(a)
        self._H(a)

    def _SY(self, a: int) -> None:
        """√Y = S†·√X†·S."""
        self._S(a)
        self._SXdg(a)
        self._Sdg(a)

    def _SYdg(self, a: int) -> None:
        """√Y† = S†·√X·S."""
        self._S(a)
        self._SX(a)
        self._Sdg(a)

    # ------------------------------------------------------------------
    # Gate dispatch
    # ------------------------------------------------------------------

    def _apply_1q(self, name: str, a: int) -> None:
        getattr(self, "_" + name)(a)

    def _apply_2q(self, name: str, a: int, b: int) -> None:
        getattr(self, "_" + name)(a, b)

    def apply_gate(self, gate: str, targets: list[int]) -> None:
        """Apply a named gate to the given targets.

        Single-qubit gates are broadcast: each qubit in ``targets`` receives
        the gate in order. Two-qubit gates require exactly two targets.

        Gate names must be in the supported set (see module docstring).
        """
        if gate in _1Q:
            for t in targets:
                self._apply_1q(gate, int(t))
            return
        if gate in _2Q:
            if len(targets) != 2:
                raise ValueError(f"{gate} expects 2 targets, got {len(targets)}")
            self._apply_2q(gate, int(targets[0]), int(targets[1]))
            return
        raise ValueError(f"Unsupported gate: '{gate}'. Supported: {sorted(_1Q | _2Q)}")

    # ------------------------------------------------------------------
    # Rowsum: multiply Pauli row i into row h, tracking phase (Aaronson eq. 9)
    # ------------------------------------------------------------------

    def _rowsum(self, h: int, i: int) -> None:
        xi = self.x[i].astype(np.int64)
        zi = self.z[i].astype(np.int64)
        xh = self.x[h].astype(np.int64)
        zh = self.z[h].astype(np.int64)

        g = np.zeros(self.n, dtype=np.int64)
        m11 = (xi == 1) & (zi == 1)
        m10 = (xi == 1) & (zi == 0)
        m01 = (xi == 0) & (zi == 1)
        g[m11] = zh[m11] - xh[m11]
        g[m10] = zh[m10] * (2 * xh[m10] - 1)
        g[m01] = xh[m01] * (1 - 2 * zh[m01])

        total = (2 * int(self.r[h]) + 2 * int(self.r[i]) + int(g.sum())) % 4
        self.r[h] = 1 if total == 2 else 0
        self.x[h] ^= self.x[i]
        self.z[h] ^= self.z[i]

    # ------------------------------------------------------------------
    # Z-basis measurement (destructive; random when anticommuting stabilizer
    # exists, deterministic otherwise)
    # ------------------------------------------------------------------

    def _measure_z(self, a: int) -> int:
        n, m = self.n, self._M
        stab_rows = np.nonzero(self.x[n:m, a])[0]
        if stab_rows.size > 0:
            # Random outcome: there is a stabilizer that anticommutes with Z_a.
            p = n + int(stab_rows[0])
            for i in np.nonzero(self.x[:m, a])[0]:
                if int(i) != p:
                    self._rowsum(int(i), p)
            self.x[p - n] = self.x[p].copy()
            self.z[p - n] = self.z[p].copy()
            self.r[p - n] = self.r[p]
            self.x[p, :] = 0
            self.z[p, :] = 0
            self.z[p, a] = 1
            self.r[p] = int(np.random.randint(2))
            return int(self.r[p])
        # Deterministic outcome: accumulate in scratch row.
        self.x[m, :] = 0
        self.z[m, :] = 0
        self.r[m] = 0
        for i in np.nonzero(self.x[:n, a])[0]:
            self._rowsum(m, n + int(i))
        return int(self.r[m])

    # ------------------------------------------------------------------
    # Expectation value of a product of Z operators (non-destructive)
    # ------------------------------------------------------------------

    def _expect_z_set(self, qubits: list[int]) -> float:
        """Return ⟨⊗_{q∈qubits} Z_q⟩ without disturbing the state.

        Returns 0 if the operator anticommutes with any stabilizer (i.e. the
        expectation is zero in any stabilizer state), else ±1.
        """
        n, m = self.n, self._M
        if not qubits:
            return 1.0
        cols = list(qubits)
        if np.any(self.x[n:m][:, cols].sum(axis=1) % 2):
            return 0.0
        self.x[m, :] = 0
        self.z[m, :] = 0
        self.r[m] = 0
        parity = self.x[:n][:, cols].sum(axis=1) % 2
        for i in np.nonzero(parity)[0]:
            self._rowsum(m, n + int(i))
        return -1.0 if self.r[m] else 1.0

    # ------------------------------------------------------------------
    # Public expectation / measurement interface
    # ------------------------------------------------------------------

    def pauli_expectation(self, paulis: dict[int, str]) -> float:
        """Return ⟨P⟩ for a tensor-product Pauli P = ⊗ P_q, non-destructive.

        ``paulis`` maps qubit index → basis letter ``'X'``, ``'Y'``, or ``'Z'``.
        Qubits not in the dict are treated as identity.

        Strategy: conjugate each non-Z factor to Z via single-qubit rotations,
        evaluate ⟨Z...Z⟩ via the scratch-row method, then undo the rotations.
        """
        for q, p in paulis.items():
            if p == "X":
                self._H(q)
            elif p == "Y":
                self._Sdg(q)
                self._H(q)
        val = self._expect_z_set(list(paulis.keys()))
        for q, p in paulis.items():
            if p == "X":
                self._H(q)
            elif p == "Y":
                self._H(q)
                self._S(q)
        return val

    def expectation_pauli(self, idx: int, basis: str) -> float:
        """Return ⟨basis⟩ for a single qubit. ``basis`` ∈ {'X','Y','Z'}."""
        if basis not in ("X", "Y", "Z"):
            raise ValueError("basis must be 'X', 'Y', or 'Z'")
        return self.pauli_expectation({idx: basis})

    def measure(self, idx: int, basis: str = "Z") -> int:
        """Projectively measure qubit ``idx`` in the given basis; return 0 or 1.

        The state is updated to the post-measurement eigenstate. For basis X or Y
        the qubit is rotated to Z, measured, then rotated back.
        """
        if basis == "Z":
            return self._measure_z(idx)
        if basis == "X":
            self._H(idx)
            out = self._measure_z(idx)
            self._H(idx)
            return out
        if basis == "Y":
            self._Sdg(idx)
            self._H(idx)
            out = self._measure_z(idx)
            self._H(idx)
            self._S(idx)
            return out
        raise ValueError("basis must be 'X', 'Y', or 'Z'")
