#!/usr/bin/env python
"""Generate the PWA app icons from static/favicon.svg.

`favicon.svg` is the single source of truth for the bomb glyph. PWAs additionally
need raster icons with an opaque, full-bleed background (Chrome's install criteria
and the Play Store require 192x192 + 512x512 PNGs, and maskable icons must fill the
canvas). The favicon uses `currentColor` and has no background, so it can't be used
directly. This script:

  1. composes a 512x512 icon SVG — a solid app-theme background plus the favicon
     glyph scaled into the maskable safe zone (inner ~80%) — written to icon.svg;
  2. rasterises it to icon-192.png and icon-512.png.

So editing favicon.svg is all that's needed; the PWA icons follow. Run:

    python scripts/make_icons.py

It shells out to whichever SVG rasteriser is installed (rsvg-convert, ImageMagick
convert, or inkscape), so it works in CI and on a dev box without a Python SVG lib.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ICONS = ROOT / "src" / "qminesweeper" / "static" / "icons"
FAVICON = ROOT / "src" / "qminesweeper" / "static" / "favicon.svg"
ICON_SVG = ICONS / "icon.svg"  # generated, derived from favicon.svg

CANVAS = 512  # icon is CANVAS x CANVAS
SAFE = 0.72  # glyph fills this fraction of the canvas
# Match favicon.svg's natural look: a dark bomb (its currentColor defaults to dark)
# with a white shine + yellow spark. Transparent background (BG = None) — the home
# screen / launcher supplies its own plate behind a non-maskable icon.
BG = None  # set to a colour (e.g. "#f7f9fc") for an opaque background
FG = "#17191e"  # resolves the favicon's currentColor (the dark bomb body + fuse)

# (output filename, pixel size). 192 + 512 are the install-criteria minimums.
TARGETS = [
    ("icon-192.png", 192),
    ("icon-512.png", 512),
]


def _compose_icon_svg() -> str:
    """Build a full-bleed 512x512 icon SVG from favicon.svg's glyph."""
    fav = FAVICON.read_text(encoding="utf-8")

    # Pull the source viewBox (fall back to 64x64) to size the transform.
    m = re.search(r'viewBox\s*=\s*"([^"]+)"', fav)
    vb = m.group(1).split() if m else ["0", "0", "64", "64"]
    w, h = float(vb[2]), float(vb[3])

    # Inner markup = everything between the opening <svg ...> and closing </svg>.
    inner = fav[fav.index(">", fav.index("<svg")) + 1 : fav.rindex("</svg>")].strip()

    # favicon.svg paints the bomb/fuse with `currentColor` (it inherits the page
    # text colour as a favicon). Substitute an explicit colour: ImageMagick's SVG
    # renderer ignores `currentColor`/`color`, which would silently drop those
    # shapes — leaving only the white shine and yellow spark. Replace it directly.
    inner = inner.replace("currentColor", FG)

    # Scale the glyph into the safe zone and centre it on the canvas.
    scale = SAFE * CANVAS / max(w, h)
    tx = (CANVAS - w * scale) / 2
    ty = (CANVAS - h * scale) / 2

    background = f'  <rect width="{CANVAS}" height="{CANVAS}" fill="{BG}"/>\n' if BG else ""
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- GENERATED by scripts/make_icons.py from static/favicon.svg. Do not edit by hand. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS}" height="{CANVAS}" '
        f'viewBox="0 0 {CANVAS} {CANVAS}" fill="none">\n'
        f"{background}"
        f'  <g transform="translate({tx:.2f} {ty:.2f}) scale({scale:.4f})" color="{FG}">\n'
        f"    {inner}\n"
        "  </g>\n"
        "</svg>\n"
    )


def _candidates(src: Path, out: Path, size: int) -> list[list[str]]:
    """Rasteriser command lines to try, in preference order. Each is attempted
    until one succeeds, so a tool that is installed-but-broken (e.g. a snap
    Inkscape with a glibc mismatch) doesn't block the others."""
    cmds = []
    if shutil.which("rsvg-convert"):
        cmds.append(["rsvg-convert", "-w", str(size), "-h", str(size), "-o", str(out), str(src)])
    if shutil.which("convert"):
        # -background none keeps the SVG's own background; -density boosts quality.
        cmds.append(["convert", "-background", "none", "-density", "384",
                     "-resize", f"{size}x{size}", str(src), str(out)])
    if shutil.which("inkscape"):
        cmds.append(["inkscape", str(src), "-w", str(size), "-h", str(size),
                     "--export-type=png", f"--export-filename={out}"])
    return cmds


def _rasterise(src: Path, out: Path, size: int) -> None:
    """Render `src` SVG to a `size`x`size` PNG using the first tool that works."""
    cmds = _candidates(src, out, size)
    if not cmds:
        sys.exit("No SVG rasteriser found (need rsvg-convert, convert, or inkscape).")
    for cmd in cmds:
        try:
            subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            if out.exists() and out.stat().st_size > 0:
                return
        except (subprocess.CalledProcessError, OSError):
            continue
    sys.exit(f"All rasterisers failed for {out.name}; tried: {[c[0] for c in cmds]}")


def main() -> None:
    if not FAVICON.exists():
        sys.exit(f"Missing glyph source: {FAVICON}")
    ICONS.mkdir(parents=True, exist_ok=True)
    ICON_SVG.write_text(_compose_icon_svg(), encoding="utf-8")
    print(f"  composed {ICON_SVG.relative_to(ROOT)} from {FAVICON.relative_to(ROOT)}")
    for name, size in TARGETS:
        out = ICONS / name
        _rasterise(ICON_SVG, out, size)
        print(f"  {out.relative_to(ROOT)}  ({size}x{size})")
    print(f"Generated {len(TARGETS)} PNG icons from {FAVICON.relative_to(ROOT)}.")


if __name__ == "__main__":
    main()
