name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: qminesweeper
          
      - name: Install package
        shell: bash -l {0}
        run: pip install -e .

      - name: Run pytest with coverage
        shell: bash -l {0}
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=qminesweeper --cov-report=xml

    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v4
    #     with:
    #       files: ./coverage.xml
    #       fail_ci_if_error: false
